
WORDS = {
        # Clothing & Accessories
    "vaate": "clothes", "paita": "shirt", "housut": "pants", "hame": "skirt", "mekko": "dress",
    "takki": "jacket", "hattu": "hat", "pipo": "beanie", "käsine": "glove", "sukka": "sock",
    "kenkä": "shoe", "saapas": "boot", "vyö": "belt", "huivi": "scarf", "solmio": "tie",
    "puku": "suit", "uimapuku": "swimsuit", "alusvaatteet": "underwear", "tasku": "pocket",
    "nappi": "button", "vetoketju": "zipper", "sateenvarjo": "umbrella", "laukku": "bag",
    "reppu": "backpack", "lompakko": "wallet", "silmälasit": "glasses", "sormus": "ring",
    "korvakorut": "earrings", "kaulakoru": "necklace", "rannekello": "wristwatch",

    # Nature & Weather (Extended)
    "maailma": "world", "avaruus": "space", "planeetta": "planet", "ilmasto": "climate",
    "sää": "weather", "lämpötila": "temperature", "aste": "degree", "helle": "heatwave",
    "pakkanen": "freezing weather", "sumu": "fog", "kaste": "dew", "raekuuro": "hail",
    "salama": "lightning", "myrsky": "storm", "tulva": "flood", "maanjäristys": "earthquake",
    "tulivuori": "volcano", "aavikko": "desert", "viidakko": "jungle", "luola": "cave",
    "hiekkaranta": "sandy beach", "valtameri": "ocean", "aalto": "wave", "rannikko": "coast",
    "itse": "self", "energia": "energy", "ympäristö": "environment",

    # Animals (Extended)
    "orava": "squirrel", "siili": "hedgehog", "hirvi": "moose", "peura": "deer",
    "karitsa": "lamb", "vuohi": "goat", "ankka": "duck", "hanhi": "goose",
    "kana": "hen", "kukko": "rooster", "pöllö": "owl", "kotka": "eagle",
    "varis": "crow", "harakka": "magpie", "pääskynen": "swallow", "muurahainen": "ant",
    "mehiläinen": "bee", "hämähäkki": "spider", "itikka": "mosquito", "perhonen": "butterfly",
    "valas": "whale", "hylje": "seal", "rapu": "crab", "etana": "snail",

    # School, Work & Media
    "opiskelija": "student", "opettaja": "teacher", "rehtori": "principal", "luokka": "class",
    "kurssi": "course", "koe": "test", "arvosana": "grade", "läksyt": "homework",
    "kynä": "pen", "lyijykynä": "pencil", "pyyhekumi": "eraser", "viivatin": "ruler",
    "vihko": "notebook", "kirja": "book", "sanakirja": "dictionary", "paperi": "paper",
    "tussi": "marker", "liitu": "chalk", "tietotaito": "know-how", "ammatti": "profession",
    "palkka": "salary", "loma": "holiday", "kokous": "meeting", "sopimus": "contract",
    "asiakas": "customer", "pomo": "boss", "työpaikka": "workplace", "yritys": "company",
    "uutiset": "news", "sanomalehti": "newspaper", "aikakauslehti": "magazine", "mainos": "advertisement",

    # Verbs (as Nouns/Actions)
    "juoksu": "running", "uinti": "swimming", "laulu": "singing", "tanssi": "dance",
    "puhe": "speech", "ajatus": "thought", "muisto": "memory", "uni": "dream",
    "toivo": "hope", "pelko": "fear", "viha": "hate", "suru": "sadness",
    "nauru": "laughter", "itku": "crying", "liike": "movement", "matka": "journey",
    "leikki": "play", "peli": "game", "voitto": "victory", "häviö": "loss",

    # Adjectives (as concepts) & Colors
    "punainen": "red", "sininen": "blue", "vihreä": "green", "keltainen": "yellow",
    "musta": "black", "valkoinen": "white", "harmaa": "gray", "ruskea": "brown",
    "oranssi": "orange", "violetti": "purple", "vaaleanpunainen": "pink", "kulta": "gold",
    "hopea": "silver", "koko": "size", "pituus": "length", "leveys": "width",
    "korkeus": "height", "paino": "weight", "muoto": "shape", "maku": "taste",
    "haju": "smell", "tunto": "touch",

    # Tools & Objects
    "vasara": "hammer", "saha": "saw", "ruuvimeisseli": "screwdriver", "naula": "nail (tool)",
    "ruuvi": "screw", "sakset": "scissors", "teippi": "tape", "liima": "glue",
    "ämpäri": "bucket", "harja": "brush", "luuta": "broom", "lapio": "shovel",
    "tikkaat": "ladder", "akku": "battery", "johto": "cord", "pistorasia": "socket",
    "tulitikut": "matches", "sytytin": "lighter", "kynttilä": "candle", "taskulamppu": "flashlight",
    # Animals & Nature
    "koira": "dog", "kissa": "cat", "hevonen": "horse", "lehmä": "cow", "lammas": "sheep",
    "sika": "pig", "karhu": "bear", "susi": "wolf", "kettu": "fox", "jänis": "hare",
    "lintu": "bird", "kala": "fish", "käärme": "snake", "hyönteinen": "insect", "puu": "tree",
    "kukka": "flower", "metsä": "forest", "järvi": "lake", "meri": "sea", "joki": "river",
    "vuori": "mountain", "mäki": "hill", "saari": "island", "niemi": "peninsula", "ranta": "shore",
    "taivas": "sky", "aurinko": "sun", "kuu": "moon", "tähti": "star", "pilvi": "cloud",
    "sade": "rain", "lumi": "snow", "jää": "ice", "tuuli": "wind", "ukkonen": "thunder",
    "kivi": "stone", "hiekka": "sand", "multa": "soil", "ruoho": "grass", "lehti": "leaf",
    "oksa": "branch", "juuri": "root", "marja": "berry", "sieni": "mushroom", "puro": "brook",
    "lähde": "spring", "suo": "swamp", "tunturi": "fell", "luonto": "nature",
    
    # People & Family
    "mies": "man", "nainen": "woman", "lapsi": "child", "poika": "boy", "tyttö": "girl",
    "vauva": "baby", "isä": "father", "äiti": "mother", "veli": "brother", "sisko": "sister",
    "tytär": "daughter", "isoäiti": "grandmother", "isoisä": "grandfather", "serkku": "cousin",
    "täti": "aunt", "setä": "uncle (paternal)", "eno": "uncle (maternal)", "perhe": "family",
    "suku": "relatives", "ystävä": "friend", "naapuri": "neighbor", "ihminen": "human",
    "henkilö": "person", "vieras": "guest", "isäntä": "host", "emäntä": "hostess", "vaimo": "wife",
    "pari": "couple",
    
    # Body Parts
    "pää": "head", "silmä": "eye", "korva": "ear", "nenä": "nose", "suu": "mouth",
    "huuli": "lip", "hammas": "tooth", "kieli": "tongue", "kaula": "neck",
    "kurkku": "throat", "olkapää": "shoulder", "käsivarsi": "arm", "käsi": "hand",
    "sormi": "finger", "kynsi": "nail", "rinta": "chest", "vatsa": "stomach", "selkä": "back",
    "jalka": "leg", "polvi": "knee", "varvas": "toe", "iho": "skin", "luu": "bone",
    "veri": "blood", "sydän": "heart", "keuhko": "lung", "lihas": "muscle", "naama": "face",
    
    # House & Household
    "talo": "house", "koti": "home", "asunto": "apartment", "huone": "room", "keittiö": "kitchen",
    "kylpyhuone": "bathroom", "makuuhuone": "bedroom", "olohuone": "living room", "eteinen": "hall",
    "parveke": "balcony", "piha": "yard", "ovi": "door", "ikkuna": "window", "seinä": "wall",
    "katto": "roof", "lattia": "floor", "porras": "stair", "lukko": "lock", "avain": "key",
    "pöytä": "table", "tuoli": "chair", "sänky": "bed", "sohva": "sofa", "kaappi": "cabinet",
    "hylly": "shelf", "lamppu": "lamp", "matto": "carpet", "verho": "curtain", "peili": "mirror",
    "taulu": "picture", "kello": "clock", "radio": "radio", "televisio": "television",
    "tietokone": "computer", "puhelin": "telephone", "kone": "machine", "uuni": "oven",
    "hella": "stove", "allas": "basin",
    
    # Kitchen & Food
    "ruoka": "food", "juoma": "drink", "vesi": "water", "maito": "milk", "kahvi": "coffee",
    "tee": "tea", "mehu": "juice", "olut": "beer", "viini": "wine", "leipä": "bread",
    "voi": "butter", "juusto": "cheese", "liha": "meat", "kana": "chicken", "muna": "egg",
    "makkara": "sausage", "peruna": "potato", "riisi": "rice", "pasta": "pasta",
    "vihannes": "vegetable", "hedelmä": "fruit", "omena": "apple", "banaani": "banana",
    "suola": "salt", "sokeri": "sugar", "jauho": "flour", "öljy": "oil", "kastike": "sauce",
    "lautanen": "plate", "kulho": "bowl", "lasi": "glass", "muki": "mug", "kuppi": "cup",
    "veitsi": "knife", "haarukka": "fork", "lusikka": "spoon", "kattila": "pot", "pannu": "pan",

    # Transportation & City
    "auto": "car", "bussi": "bus", "juna": "train", "lentokone": "airplane", "laiva": "ship",
    "vene": "boat", "pyörä": "bicycle", "moottoripyörä": "motorcycle", "tie": "road", "katu": "street",
    "polku": "path", "silta": "bridge", "tunneli": "tunnel", "asema": "station", "satama": "harbor",
    "tori": "market", "puisto": "park", "kaupunki": "city", "kylä": "village", "maa": "country",
    "valtio": "state", "raja": "border", "keskusta": "center", "kauppa": "shop", "pankki": "bank",
    "sairaala": "hospital", "koulu": "school", "kirkko": "church", "tehdas": "factory",
    "hotelli": "hotel", "ravintola": "restaurant", "kahvila": "cafe", "museo": "museum",
    "kirjasto": "library", "teatteri": "theater", "poliisi": "police", "posti": "post", "apteekki": "pharmacy",

    # Time & Abstract
    "aika": "time", "hetki": "moment", "sekunti": "second", "minuutti": "minute", "tunti": "hour",
    "päivä": "day", "viikko": "week", "kuukausi": "month", "vuosi": "year", "vuosisata": "century",
    "aamu": "morning", "ilta": "evening", "yö": "night", "maanantai": "Monday", "tiistai": "Tuesday",
    "keskiviikko": "Wednesday", "torstai": "Thursday", "perjantai": "Friday", "lauantai": "Saturday",
    "sunnuntai": "Sunday", "kevät": "spring", "kesä": "summer", "syksy": "autumn", "talvi": "winter",
    "asia": "thing", "sana": "word", "nimi": "name", "numero": "number", "väri": "color",
    "ääni": "sound", "valo": "light", "elämä": "life", "onni": "happiness", "rakkaus": "love",
    "työ": "work", "raha": "money", "ongelma": "problem", "vastaus": "answer", "kysymys": "question","maksa": "liver", "munuainen": "kidney", "luu": "bone", "nivel": "joint",
    "verisuoni": "blood vessel", "hermo": "nerve", "iho": "skin", "otsa": "forehead", "leuka": "chin",
    "poski": "cheek", "kulmakarva": "eyebrow", "ripsi": "eyelash", "napa": "navel", "vyötärö": "waist",
    "kyynärpää": "elbow", "ranne": "wrist", "kämmen": "palm", "lantio": "pelvis", "reisi": "thigh",
    "pohje": "calf", "nilkka": "ankle", "kantapää": "heel", "terveystarkastus": "check-up", "lääke": "medicine",
    "resepti": "prescription", "kuume": "fever", "yskä": "cough", "nuha": "cold (flu)", "haava": "wound",
    "side": "bandage", "leikkaus": "surgery", "kipulääke": "painkiller", "vitamiini": "vitamin", "allergia": "allergy",    "pusero": "blouse", "huppari": "hoodie", "neule": "knitwear", "liivi": "vest", "uimahousut": "swim trunks",
    "yöpaita": "nightshirt", "pyjama": "pajamas", "kravatti": "necktie", "rusetti": "bow tie", "kaulaliina": "scarf",
    "lapanen": "mitten", "sormikas": "glove (with fingers)", "lenkkarit": "sneakers", "korkokengät": "high heels", "sandaali": "sandal",
    "tohveli": "slipper", "kumisaapas": "rubber boot", "henkselit": "suspenders", "solki": "buckle", "hihna": "strap",
    "hiha": "sleeve", "lahje": "trouser leg", "kaulus": "collar", "vuori": "lining (clothes)", "kangas": "fabric",
    "villa": "wool", "puuvilla": "cotton", "silkki": "silk", "pellava": "linen", "nahka": "leather",    "astianpesukone": "dishwasher", "pyykinpesukone": "washing machine", "pakastin": "freezer", "mikroaaltouuni": "microwave", "leivänpaahdin": "toaster",
    "vedenkeitin": "kettle", "tehosekoitin": "blender", "vatkain": "mixer", "kahvinkeitin": "coffee maker", "imuri": "vacuum cleaner",
    "silitysrauta": "iron", "laatikko": "drawer", "tiskiallas": "sink", "hana": "faucet", "roskakori": "trash can",
    "talouspaperi": "paper towel", "tiskiharja": "dish brush", "pesuaine": "detergent", "sieni": "sponge", "liina": "cloth",
    "verho": "curtain", "tyyny": "pillow", "peitto": "blanket", "lakana": "sheet", "pyyhe": "towel",
    "matto": "rug", "henkari": "hanger", "peili": "mirror", " kampa": "comb", "hammasharja": "toothbrush",    "sipuli": "onion", "valkosipuli": "garlic", "porkkana": "carrot", "kurkku": "cucumber", "tomaatti": "tomato",
    "paprika": "bell pepper", "salaatti": "lettuce", "kaali": "cabbage", "herne": "pea", "papu": "bean",
    "maissi": "corn", "peruna": "potato", "päärynä": "pear", "luumu": "plum", "viinirypäle": "grape",
    "mansikka": "strawberry", "mustikka": "blueberry", "vadelma": "raspberry", "sitruuna": "lemon", "appelsiini": "orange",
    "pähkinä": "nut", "siemen": "seed", "hunaja": "honey", "hillo": "jam", "sinappi": "mustard",
    "ketsuppi": "ketchup", "pippuri": "pepper", "mauste": "spice", "kerma": "cream", "rahka": "quark",
    "jogurtti": "yogurt", "hiiva": "yeast", "leivonnainen": "pastry", "kakku": "cake", "keksi": "cookie",    "näyttö": "monitor", "näppäimistö": "keyboard", "hiiri": "mouse", "tulostin": "printer", "laturi": "charger",
    "akku": "battery", "kaapeli": "cable", "kuulokkeet": "headphones", "kaiutin": "speaker", "kaukosäädin": "remote control",
    "sovellus": "application", "tiedosto": "file", "kansio": "folder", "salasana": "password", "viesti": "message",
    "sähköposti": "email", "internetyhteys": "internet connection", "vasara": "hammer", "ruuvi": "screw", "mutteri": "nut (tool)",
    "pihdit": "pliers", "avain": "wrench/key", "mittanauha": "tape measure", "vatupassi": "spirit level", "porakone": "drill",    "ilves": "lynx", "hirvi": "moose", "poro": "reindeer", "siili": "hedgehog", "orava": "squirrel",
    "myyrä": "mole", "lepakko": "bat", "joutsen": "swan", "sorsa": "duck", "lokki": "gull",
    "pääskynen": "swallow", "tikka": "woodpecker", "varis": "crow", "harakka": "magpie", "pöllö": "owl",
    "perhonen": "butterfly", "kimalainen": "bumblebee", "muurahainen": "ant", "itikka": "mosquito", "kärpänen": "fly",
    "mato": "worm", "etana": "snail", "sammakko": "frog", "sisilisko": "lizard", "koivu": "birch",
    "mänty": "pine", "kuusi": "spruce", "tammi": "oak", "vaahtera": "maple", "pihlaja": "rowan",    "liikenne": "traffic", "ruuhka": "traffic jam", "kulkuneuvo": "vehicle", "perävaunu": "trailer", "polkupyörä": "bicycle",
    "jalankulkija": "pedestrian", "suojatie": "crosswalk", "liikennevalo": "traffic light", "pysäköinti": "parking", "sakko": "fine",
    "lippu": "ticket", "matkalippu": "travel ticket", "passi": "passport", "matkalaukku": "suitcase", "reppu": "backpack",
    "lentokenttä": "airport", "rautatieasema": "railway station", "laituri": "platform", "kiitotie": "runway", "tulli": "customs",
    "turisti": "tourist", "opas": "guide", "kartta": "map", "suunta": "direction", "kohde": "destination",    "opiskelu": "studying", "opetus": "teaching", "luento": "lecture", "harjoitus": "exercise", "tutkinto": "degree",
    "todistus": "certificate", "ammattikoulu": "vocational school", "yliopisto": "university", "tiede": "science", "tutkimus": "research",
    "historia": "history", "maantieto": "geography", "matematiikka": "mathematics", "kieli": "language", "kirjallisuus": "literature",
    "työhakemus": "job application", "haastattelu": "interview", "ura": "career", "eläke": "pension", "työttömyys": "unemployment",
    "vero": "tax", "lasku": "bill", "kuitti": "receipt", "sopimus": "contract", "allekirjoitus": "signature",
    "laki": "law", "oikeus": "justice", "rikos": "crime", "rangaistus": "punishment", "vankila": "prison",    "urheilu": "sports", "liikunta": "physical exercise", "jalkapallo": "football", "jääkiekko": "ice hockey", "hiihto": "skiing",
    "luistelu": "skating", "uinti": "swimming", "kuntosali": "gym", "joukkue": "team", "kilpailu": "competition",
    "musiikki": "music", "soitin": "musical instrument", "kitara": "guitar", "piano": "piano", "rummut": "drums",
    "laulaja": "singer", "konsertti": "concert", "elokuva": "movie", "teatteri": "theater", "näyttely": "exhibition",
    "maalaus": "painting", "valokuva": "photograph", "kamera": "camera", "lukeminen": "reading", "kirjailija": "author",    "mahdollisuus": "opportunity", "syy": "reason", "seuraus": "consequence", "tarkoitus": "purpose", "mielipide": "opinion",
    "tieto": "knowledge", "taito": "skill", "kokemus": "experience", "muutos": "change", "kehitys": "development",
    "tulevaisuus": "future", "menneisyys": "past", "nykyhetki": "present", "alku": "beginning", "loppu": "end",
    "vapaus": "freedom", "rauha": "peace", "sota": "war", "turvallisuus": "safety", "vaara": "danger",
    "totuus": "truth", "valhe": "lie", "salaisuus": "secret", "onni": "happiness/luck", "suru": "sorrow",    "katto": "roof/ceiling", "lattia": "floor", "seinä": "wall", "ikkuna": "window", "ovi": "door",
    "kahva": "handle", "porras": "step/stair", "hissi": "elevator", "kellari": "basement", "ullakko": "attic",
    "sauna": "sauna", "laude": "sauna bench", "kiuas": "sauna stove", "kylpyamme": "bathtub", "suihku": "shower",
    "vessa": "toilet (colloquial)", "pistorasia": "electric socket", "katkaisija": "switch", "lamppu": "lamp", "valaisin": "light fixture",
    "pöytäliina": "tablecloth", "maljakko": "vase", "kehys": "frame", "ruukku": "pot", "multa": "soil",    "ennuste": "forecast", "pouta": "fair weather", "pilvi": "cloud", "usva": "mist", "sumu": "fog",
    "pakkanen": "frost/freezing weather", "suojasää": "thaw", "helle": "heat", "ukkonen": "thunder", "salama": "lightning",
    "myrsky": "storm", "rajuilma": "severe storm", "lumisade": "snowfall", "räntä": "sleet", "raepilvi": "hail cloud",
    "tähti": "star", "planeetta": "planet", "galaksi": "galaxy", "avaruus": "space", "kiertorata": "orbit",    "punkki": "tick", "paarma": "horsefly", "mehiläinen": "bee", "ampiainen": "wasp", "lude": "bedbug",
    "koiruoho": "wormwood", "sammal": "moss", "jäkälä": "lichen", "varpu": "dwarf shrub", "heinä": "hay",
    "apila": "clover", "voikukka": "dandelion", "ruusu": "rose", "tulppaani": "tulip", "lilja": "lily",    "eteinen": "hallway", "makuuhuone": "bedroom", "vaatehuone": "walk-in closet", "parveke": "balcony", "terassi": "terrace",
    "kynnys": "threshold", "sarana": "hinge", "ikkunalauta": "windowsill", "savupiippu": "chimney", "tulipesä": "firebox",
    "takka": "fireplace", "leivinuuni": "masonry oven", "patteri": "radiator", "ilmanvaihto": "ventilation", "viemäri": "drain",
    "vesijohto": "water pipe", "sulake": "fuse", "jatkojohto": "extension cord", "pölynimuri": "vacuum cleaner", "pyykkipoika": "clothespin",
    "silityslauta": "ironing board", "henkari": "coat hanger", "kenkälusikka": "shoehorn", "ovikello": "doorbell", "postilaatikko": "mailbox",    "paistinpannu": "frying pan", "kattila": "pot", "uunipelti": "baking sheet", "raastinrauta": "grater", "siivilä": "strainer",
    "kaulin": "rolling pin", "leikkuulauta": "cutting board", "purkinavaaja": "can opener", "korkkiruuvi": "corkscrew", "lasta": "spatula",
    "vispilä": "whisk", "kauha": "ladle", "mittakuppi": "measuring cup", "vaaka": "scale", "talouspaperi": "kitchen roll",
    "folio": "foil", "leivinpaperi": "parchment paper", "elintarvike": "foodstuff", "ainesosa": "ingredient", "mauste": "spice",
    "kaneli": "cinnamon", "pippuri": "pepper", "inkivääri": "ginger", "valkosipuli": "garlic", "sipuli": "onion",    "vehnä": "wheat", "ruis": "rye", "kaura": "oat", "ohra": "barley", "tattari": "buckwheat",
    "hiiva": "yeast", "leivinjauhe": "baking powder", "hunaja": "honey", "siirappi": "syrup", "etikka": "vinegar",
    "sinappi": "mustard", "majoneesi": "mayonnaise", "liemi": "broth", "kerma": "cream", "viili": "viili (curd)",
    "rahka": "quark", "voi": "butter", "margariini": "margarine", "levite": "spread", "leikkele": "cold cut",
    "savukala": "smoked fish", "katkarapu": "shrimp", "simpukka": "mussel", "lohi": "salmon", "siika": "whitefish",    "kanto": "stump", "neulanen": "needle (pine)", "käpy": "cone", "tuohi": "birch bark", "kaarna": "bark",
    "sammal": "moss", "jäkälä": "lichen", "varpu": "shrub", "kanerva": "heather", "heinä": "hay",
    "olki": "straw", "pelto": "field", "niitty": "meadow", "laidun": "pasture", "oja": "ditch",
    "lampi": "pond", "lahti": "bay", "salmi": "strait", "koski": "rapids", "vesiputous": "waterfall",
    "luola": "cave", "jyrkänne": "cliff", "huippu": "peak", "rinne": "slope", "laakso": "valley",    "nisäkäs": "mammal", "jyrsijä": "rodent", "päästäinen": "shrew", "myyrä": "vole", "mäyrä": "badger",
    "näätä": "marten", "saukko": "otter", "hylje": "seal", "valas": "whale", "poro": "reindeer",
    "hirvi": "moose", "kauris": "roe deer", "ilves": "lynx", "susi": "wolf", "karhu": "bear",
    "kettu": "fox", "supikoira": "raccoon dog", "jänis": "hare", "kani": "rabbit", "orava": "squirrel",
    "siili": "hedgehog", "lepakko": "bat", "kyy": "viper", "rantakäärme": "grass snake", "sammakko": "frog",    "aluspaita": "undershirt", "uimapuku": "swimsuit", "kylpytakki": "bathrobe", "pipo": "beanie", "lippalakki": "cap",
    "lierihattu": "brimmed hat", "huivi": "scarf", "kaulaliina": "muffler", "solmio": "tie", "vyö": "belt",
    "olkihattu": "straw hat", "sadetakki": "raincoat", "toppa": "padding", "vuori": "lining", "hiha": "sleeve",
    "kaulus": "collar", "tasku": "pocket", "nappi": "button", "vetoketju": "zipper", "nauha": "lace",    "vasara": "hammer", "saha": "saw", "pora": "drill", "ruuvimeisseli": "screwdriver", "pihti": "pliers",
    "jakoavain": "wrench", "viila": "file", "hiomapaperi": "sandpaper", "liima": "glue", "teippi": "tape",
    "naula": "nail", "ruuvi": "screw", "mutteri": "nut", "pultti": "bolt", "aluslevy": "washer",
    "lapio": "shovel", "harava": "rake", "kuokka": "hoe", "kirves": "axe", "viikate": "scythe",
    "kottikärry": "wheelbarrow", "tikapuu": "ladder", "ämpäri": "bucket", "sanko": "pail", "letku": "hose",    "lääke": "medicine", "tabletti": "tablet", "pilleri": "pill", "voide": "ointment", "laastari": "band-aid",
    "side": "bandage", "ruisku": "syringe", "neula": "needle", "kuumemittari": "thermometer", "resepti": "prescription",
    "sairaus": "illness", "oire": "symptom", "kipu": "pain", "särky": "ache", "tulehdus": "inflammation",
    "haava": "wound", "ruhje": "bruise", "murtuma": "fracture", "leikkaus": "surgery", "nukutus": "anesthesia",
    "potilas": "patient", "lääkäri": "doctor", "hoitaja": "nurse", "sairaala": "hospital", "terveyskeskus": "clinic",    "ajoneuvo": "vehicle", "perävaunu": "trailer", "asuntovaunu": "caravan", "pakettiauto": "van", "kuorma-auto": "truck",
    "rekka": "semi-truck", "moottoripyörä": "motorcycle", "mopo": "moped", "skootteri": "scooter", "polkupyörä": "bicycle",
    "juna": "train", "veturi": "locomotive", "vaunu": "carriage", "ratikka": "tram", "metro": "subway",
    "lentokone": "airplane", "helikopteri": "helicopter", "laiva": "ship", "vene": "boat", "lautta": "ferry",
    "satama": "harbor", "laituri": "pier", "kiitotie": "runway", "torni": "tower", "asema": "station",    "tietokone": "computer", "läppäri": "laptop", "näyttö": "monitor", "näppäimistö": "keyboard", "hiiri": "mouse",
    "tulostin": "printer", "skanneri": "scanner", "laturi": "charger", "johto": "cable", "akku": "battery",
    "muistitikku": "USB drive", "kovalevy": "hard drive", "sovellus": "application", "tiedosto": "file", "kansio": "folder",
    "paperiliitin": "paperclip", "nitoja": "stapler", "rei'itin": "hole puncher", "kynä": "pen", "lyijykynä": "pencil",
    "pyyhekumi": "eraser", "viivatin": "ruler", "teroitin": "sharpener", "vihko": "notebook", "kansio": "folder",    "elokuva": "movie", "teatteri": "theater", "konsertti": "concert", "näyttely": "exhibition", "museo": "museum",
    "kirjasto": "library", "galleria": "galleria", "sirkus": "circus", "tapahtuma": "event", "juhla": "party",
    "harrastus": "hobby", "urheilu": "sports", "liikunta": "physical activity", "peli": "game", "lelu": "toy",
    "nukke": "doll", "pallo": "ball", "maila": "racket/bat", "verkko": "net", "maali": "goal",
    "voitto": "victory", "tappio": "defeat", "palkinto": "prize", "mitali": "medal", "pokaali": "trophy",    "valtio": "state", "hallitus": "government", "eduskunta": "parliament", "laki": "law", "oikeus": "right/justice",
    "rikos": "crime", "rangaistus": "punishment", "sakko": "fine", "vankila": "prison", "poliisi": "police",
    "armeija": "army", "sota": "war", "rauha": "peace", "vaali": "election", "ääni": "vote",
    "kansalainen": "citizen", "veronmaksaja": "taxpayer", "työntekijä": "employee", "työnantaja": "employer", "palkka": "salary",
    "lasku": "invoice", "kuitti": "receipt", "sopimus": "contract", "allekirjoitus": "signature", "leima": "stamp",    "ajatus": "thought", "muisto": "memory", "uni": "dream", "toive": "wish", "pelko": "fear",
    "viha": "hate", "rakkaus": "love", "suru": "sorrow", "ilo": "joy", "onni": "happiness",
    "rauha": "peace", "kiire": "hurry", "rauha": "calm", "luottamus": "trust", "epäilys": "doubt",
    "totuus": "truth", "valhe": "lie", "salaisuus": "secret", "tieto": "knowledge", "taito": "skill",
    "kokemus": "experience", "syy": "reason", "seuraus": "consequence", "tarkoitus": "purpose", "mielipide": "opinion",    "hetki": "moment", "sekunti": "second", "minuutti": "minute", "tunti": "hour", "päivä": "day",
    "viikko": "week", "kuukausi": "month", "vuosi": "year", "vuosikymmen": "decade", "vuosisata": "century",
    "aamu": "morning", "päivä": "daytime", "ilta": "evening", "yö": "night", "aamuyö": "small hours",
    "alku": "beginning", "loppu": "end", "tauko": "break", "loma": "vacation", "arkipäivä": "weekday",
    "viikonloppu": "weekend", "vuodenaika": "season", "kevät": "spring", "kesä": "summer", "syksy": "autumn",
    "talvi": "winter", "nykyhetki": "present", "tulevaisuus": "future", "menneisyys": "past", "viive": "delay",    "väri": "color", "sävy": "shade", "valo": "light", "varjo": "shadow", "pimeys": "darkness",
    "koko": "size", "pituus": "length", "leveys": "width", "korkeus": "height", "syvyys": "depth",
    "paino": "weight", "muoto": "shape", "maku": "taste", "haju": "smell", "tuoksu": "scent",
    "ääni": "sound", "melu": "noise", "hiljaisuus": "silence", "lämpö": "heat", "kylmyys": "coldness",
    "pehmeys": "softness", "kovuus": "hardness", "nopeus": "speed", "voima": "power", "energia": "energy",    "esine": "object", "kappale": "piece/item", "osa": "part", "pinta": "surface", "reuna": "edge",
    "kulma": "corner", "pohja": "bottom", "kansi": "lid", "sisältö": "content", "puoli": "side",
    "rivi": "row", "jono": "queue", "ryhmä": "group", "joukko": "crowd", "pari": "pair",
    "yksilö": "individual", "henkilö": "person", "ihminen": "human", "olento": "creature", "henki": "spirit",
    "laji": "species", "tyyppi": "type", "malli": "model", "merkki": "brand/mark", "laatu": "quality",    "ravintola": "restaurant", "kahvila": "cafe", "baari": "bar", "ruokalista": "menu", "annos": "portion",
    "alkuruoka": "appetizer", "pääruoka": "main course", "jälkiruoka": "dessert", "juoma": "drink", "vesi": "water",
    "tarjoilija": "waiter", "kokki": "cook", "asiakas": "customer", "pöytävaraus": "reservation", "lasku": "bill",
    "tippi": "tip", "terassi": "terrace", "buffet": "buffet", "take-away": "take-away", "itsepalvelu": "self-service",
    "keittiö": "kitchen", "tilaus": "order", "maku": "taste", "tuoksu": "aroma", "suosikki": "favorite",    "rehtori": "principal", "opettaja": "teacher", "oppilas": "pupil", "opiskelija": "student", "luokka": "class",
    "oppitunti": "lesson", "välitunti": "recess", "lukujärjestys": "timetable", "koe": "exam", "arvosana": "grade",
    "todistus": "certificate", "tutkinto": "degree", "yliopisto": "university", "opisto": "college", "kirjasto": "library",
    "kirja": "book", "sivisty": "civilization", "tiede": "science", "tutkimus": "research", "koe": "experiment",
    "teoria": "theory", "fakta": "fact", "matematiikka": "mathematics", "historia": "history", "kemia": "chemistry",
    "fysiikka": "physics", "biologia": "biology", "maantieto": "geography", "kielioppi": "grammar", "sana": "word",    "ammatti": "profession", "työ": "work", "ura": "career", "palkka": "salary", "vero": "tax",
    "elinkeino": "livelihood", "yritys": "company", "osasto": "department", "toimisto": "office", "tehdas": "factory",
    "työmaa": "construction site", "pomo": "boss", "kollega": "colleague", "työntekijä": "worker", "asiakas": "client",
    "sihteeri": "secretary", "insinööri": "engineer", "lääkäri": "doctor", "poliisi": "policeman", "palomies": "firefighter",
    "myyjä": "salesperson", "kuljettaja": "driver", "lentäjä": "pilot", "merimies": "sailor", "maanviljelijä": "farmer",
    "taiteilija": "artist", "muusikko": "musician", "kirjailija": "writer", "toimittaja": "journalist", "valokuvaaja": "photographer",    "matka": "trip", "loma": "holiday", "retki": "excursion", "teltta": "tent", "reppu": "backpack",
    "matkalaukku": "suitcase", "passi": "passport", "viisumi": "visa", "lippu": "ticket", "hotelli": "hotel",
    "leirintäalue": "campsite", "uimaranta": "beach", "aurinkorasva": "sunscreen", "uimapuku": "swimsuit", "vene": "boat",
    "mela": "oar", "onki": "fishing rod", "verkko": "net", "saalis": "catch", "pallo": "ball",
    "maila": "racket", "verkko": "net (sport)", "maali": "goal", "piste": "point", "erä": "round",
    "joukkue": "team", "pelaaja": "player", "tuomari": "referee", "fani": "fan", "stadion": "stadion",    "aine": "substance", "materiaali": "material", "metalli": "metal", "rauta": "iron", "teräs": "steel",
    "kulta": "gold", "hopea": "silver", "kupari": "copper", "muovi": "plastic", "lasi": "glass",
    "kumi": "rubber", "puu": "wood", "paperi": "paper", "pahvi": "cardboard", "kangas": "fabric",
    "villa": "wool", "puuvilla": "cotton", "silkki": "silk", "nahka": "leather", "kivi": "stone",
    "betoni": "concrete", "tiili": "brick", "save": "clay", "hiekka": "sand", "multa": "soil",    "maailmankaikkeus": "universe", "avaruus": "space", "galaksi": "galaxy", "aurinkokunta": "solar system", "aurinko": "sun",
    "kuu": "moon", "tähti": "star", "planeetta": "planet", "komeetta": "comet", "asteroidi": "asteroid",
    "maa": "earth", "manner": "continent", "valtio": "country", "saari": "island", "niemi": "peninsula",
    "vuori": "mountain", "tunturi": "fell", "tulivuori": "volcano", "aavikko": "desert", "viidakko": "jungle",
    "metsä": "forest", "suo": "swamp", "pohjoinen": "north", "etelä": "south", "itä": "east", "länsi": "west",    "politiikka": "politics", "demokratia": "democracy", "vaali": "election", "ääni": "vote", "puolue": "party",
    "hallitus": "government", "presidentti": "president", "ministeri": "minister", "kansalainen": "citizen", "laki": "law",
    "oikeus": "court/right", "tuomari": "judge", "rikos": "crime", "uhri": "victim", "todistaja": "witness",
    "vankila": "prison", "poliisi": "police station", "raha": "money", "valuutta": "currency", "pankki": "bank",
    "tili": "account", "kortti": "card", "käteinen": "cash", "laina": "loan", "korko": "interest",
    "sijoitus": "investment", "pörssi": "stock exchange", "omaisuus": "property", "perintö": "inheritance", "lahja": "gift",    "keskustelu": "conversation", "puhe": "speech", "huuto": "shout", "kuiskaus": "whisper", "nauru": "laugh",
    "hymy": "smile", "itku": "cry", "uni": "sleep/dream", "ajatus": "thought", "mielipide": "opinion",
    "usko": "faith", "toivo": "hope", "rakkaus": "love", "viha": "hate", "pelko": "fear",
    "jännitys": "excitement", "yllätys": "surprise", "onni": "luck/happiness", "ilo": "joy", "suru": "sadness",
    "viisaus": "wisdom", "rohkeus": "courage", "rehellisyys": "honesty", "ystävyys": "friendship", "luottamus": "trust",
    "kauneus": "beauty", "voima": "strength", "nopeus": "speed", "äly": "intelligence", "luonne": "character",    "puutarha": "garden", "puisto": "park", "nurmikko": "lawn", "kukka": "flower", "ruusu": "rose",
    "tulppaani": "tulip", "lilja": "lily", "narsissi": "daffodil", "pensa": "bush", "puu": "tree",
    "koivu": "birch", "kuusi": "spruce", "mänty": "pine", "tammi": "oak", "vaahtera": "maple",
    "lehti": "leaf", "oksa": "branch", "runko": "trunk", "juuri": "root", "käpy": "cone",
    "siemen": "seed", "hedelmä": "fruit", "marja": "berry", "sato": "harvest", "rikkaruoho": "weed",    "hetki": "moment", "tauko": "break", "viive": "delay", "vauhti": "pace", "rytmi": "rhythm",
    "kerta": "time (occurrence)", "erä": "batch/set", "pari": "pair", "tusina": "dozen", "joukko": "group",
    "määrä": "amount", "summa": "sum", "osa": "part", "kokonaisuus": "entity", "puolikas": "half",
    "neljännes": "quarter", "ympyrä": "circle", "neliö": "square", "kolmio": "triangle", "kulma": "angle",
    "piste": "dot", "viiva": "line", "pinta": "surface", "reuna": "edge", "keskipiste": "center"
}


print(len(WORDS))